%%%-------------------------------------------------------------------
%%% @doc
%%% Reference `nova_multipart_handler' that streams a file part straight to
%%% disk, one chunk at a time, without ever holding the whole body in memory.
%%%
%%% The on-disk name is generated by this module, never derived from the
%%% client-supplied `filename' - that value is attacker controlled and using
%%% it in a path is a traversal bug (`filename => <<"../../etc/cron.d/x">>').
%%% The client's filename is only ever returned as metadata by the plugin,
%%% next to this handler's `path' result.
%%%
%%% The name is 128 bits of `crypto:strong_rand_bytes/1', not a counter - a
%%% counter (e.g. `erlang:unique_integer/1') resets on every VM restart and
%%% would let a request after a redeploy silently overwrite an earlier
%%% upload's file via `file:rename/2', which has no exclusive/no-clobber
%%% mode. Random names are unique across restarts and nodes sharing `dir'.
%%%
%%% The file is opened with `exclusive' so a pre-existing symlink at the
%%% (unpredictable, module-generated) target name is refused rather than
%%% followed - that guards the `.part' name; it is the name's
%%% unpredictability, not `exclusive', that guards the final name against
%%% collision, since rename(2) itself has no exclusive variant. It is
%%% written under the `.part' suffix and renamed to its final name only in
%%% handle_end/1 - a crash mid-write can never leave a partial file at the
%%% name a caller would trust as "done". Deployments should sweep
%%% `InitArgs.dir' for stale `*.part' files (a process crash skips
%%% handle_abort/2, same as any other cleanup-on-exit callback).
%%% @end
%%%-------------------------------------------------------------------
-module(nova_multipart_file_handler).
-behaviour(nova_multipart_handler).

-export([init/2, handle_data/2, handle_end/1, handle_abort/2]).

%% InitArgs :: #{dir := file:filename_all()}
-spec init(nova_multipart_handler:part_info(), InitArgs :: #{dir := file:filename_all()}) ->
          {ok, HandlerState :: map()} | {error, Reason :: term()}.
init(_PartInfo, #{dir := Dir}) ->
    Name = binary:encode_hex(crypto:strong_rand_bytes(16), lowercase),
    TmpPath = filename:join(Dir, <<Name/binary, ".part">>),
    FinalPath = filename:join(Dir, Name),
    case file:open(TmpPath, [write, exclusive, binary]) of
        {ok, Fd} ->
            {ok, #{fd => Fd, tmp_path => TmpPath, final_path => FinalPath}};
        {error, _} = Error ->
            Error
    end.

-spec handle_data(Data :: binary(), HandlerState :: map()) ->
          {ok, NewHandlerState :: map()} | {error, Reason :: term()}.
handle_data(Data, #{fd := Fd} = State) ->
    case file:write(Fd, Data) of
        ok -> {ok, State};
        {error, _} = Error -> Error
    end.

-spec handle_end(HandlerState :: map()) ->
          {ok, #{path := file:filename_all()}} | {error, Reason :: term()}.
handle_end(#{fd := Fd, tmp_path := TmpPath, final_path := FinalPath}) ->
    %% Never raise out of a handle_end/1 - a badmatch here would propagate
    %% out of the plugin and skip handle_abort/2, orphaning the .part file.
    case file:close(Fd) of
        ok ->
            case file:rename(TmpPath, FinalPath) of
                ok ->
                    {ok, #{path => FinalPath}};
                {error, _} = Error ->
                    _ = file:delete(TmpPath),
                    Error
            end;
        {error, _} = Error ->
            _ = file:delete(TmpPath),
            Error
    end.

-spec handle_abort(Reason :: term(), HandlerState :: map()) -> ok.
handle_abort(_Reason, #{fd := Fd, tmp_path := TmpPath}) ->
    _ = file:close(Fd),
    _ = file:delete(TmpPath),
    ok.
