name: Build and test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  ci:
    uses: Taure/erlang-ci/.github/workflows/ci.yml@v1
    with:
      otp-version: '28.0'
      rebar3-version: '3.25.0'
      otp-matrix: '["26.1", "27.1", "28.0"]'
      enable-fmt: true

  nova_request_app:
    if: github.ref != 'refs/heads/master'
    needs: [ci]
    uses: ./.github/workflows/run_nra.yml
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
    secrets: inherit
