name: vaidate PR

on: [pull_request]

jobs:
    validate:
        name: Validate PR title
        runs-on: ubuntu-latest
        steps:
            - uses: amannn/action-semantic-pull-request@v5
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                types: |
                  chore
                  feat
                  fix
                  style
                  test